# Generated by Django 5.1 on 2025-12-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
