# Generated by Django 5.1 on 2025-12-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0005_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
